const KEY='deutsch-c1-tracker-v1';
const WRITING_KEY='deutsch-c1-writing-v1';
const VERB_KEY='deutsch-c1-verbs-v1';
const ARTICLE_KEY='deutsch-c1-articles-v1';
const ARTICLE_MISTAKES_KEY='deutsch-c1-article-mistakes-v1';
const CORRECTION_KEY='deutsch-c1-corrections-v1';
const ERROR_LOG_KEY='deutsch-c1-error-log-v1';
const LAB_KEY='deutsch-c1-error-lab-v1';
const NOTES_KEY='deutsch-c1-notes-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={skills:{Grammatik:54,Sprechen:58,Schreiben:50,Hören:68,Wortschatz:62},tasks:{},minutes:0,date:''};
const day=new Date().toISOString().slice(0,10);
let state={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')};
if(state.date!==day){state.minutes=0;state.date=day}
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()};
const skills=document.querySelector('#skills');
Object.entries(state.skills).forEach(([name,value])=>{const row=document.createElement('div');row.className='skill';row.innerHTML=`<label>${name}</label><input aria-label="${name} Fortschritt" type="range" min="0" max="100" value="${value}"><output>${value}%</output>`;row.querySelector('input').addEventListener('input',e=>{state.skills[name]=+e.target.value;save()});skills.append(row)});
document.querySelectorAll('[data-task]').forEach(box=>{box.checked=!!state.tasks[box.dataset.task];box.addEventListener('change',()=>{state.tasks[box.dataset.task]=box.checked;save()})});
document.querySelectorAll('[data-minutes]').forEach(btn=>btn.addEventListener('click',()=>{state.minutes+=+btn.dataset.minutes;save()}));
document.querySelector('#resetDay').addEventListener('click',()=>{state.minutes=0;save()});
document.querySelector('#copyPhrase').addEventListener('click',async e=>{await navigator.clipboard.writeText(document.querySelector('blockquote').textContent.replace(/[„“]/g,''));e.currentTarget.textContent='Kopiert ✓';setTimeout(()=>e.currentTarget.textContent='Satz kopieren',1400)});
function render(){document.querySelectorAll('.skill').forEach(row=>{const input=row.querySelector('input');input.value=state.skills[row.querySelector('label').textContent];row.querySelector('output').textContent=input.value+'%'});const checked=Object.values(state.tasks).filter(Boolean).length;document.querySelector('#weekText').textContent=`${checked} von 4 erledigt`;document.querySelector('#weekBar').style.width=(checked*25)+'%';document.querySelector('#minutes').textContent=state.minutes;document.querySelector('#minuteBar').style.width=Math.min(100,state.minutes/50*100)+'%';const total=Math.round(Object.values(state.skills).reduce((a,b)=>a+b,0)/5);document.querySelector('#totalPercent').textContent=total+'%';document.querySelector('#ring').style.strokeDashoffset=320.44*(1-total/100)}
document.querySelector('#today').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
const prompts=['Was hat dich heute beschäftigt – und warum?','Welche Idee möchtest du in nächster Zeit verwirklichen?','Beschreibe einen Moment, in dem du dich heute wohl oder unwohl gefühlt hast.','Was hast du kürzlich über dich selbst gelernt?','Welche Entscheidung fällt dir gerade schwer? Begründe deine Gedanken.','Was ist dir bei deiner Arbeit besonders wichtig?'];
const writing=JSON.parse(localStorage.getItem(WRITING_KEY)||'{}');
const entryDate=document.querySelector('#entryDate');
const paragraph=document.querySelector('#dailyParagraph');
const status=document.querySelector('#saveStatus');
let promptIndex=new Date().getDate()%prompts.length;
entryDate.value=day;
function showPrompt(){document.querySelector('#promptText').textContent=prompts[promptIndex]}
function loadEntry(){const entry=writing[entryDate.value]||{text:'',review:{}};paragraph.value=entry.text||'';document.querySelectorAll('[data-review]').forEach(x=>x.checked=!!entry.review?.[x.dataset.review]);status.textContent=entry.text?'Gespeicherter Eintrag':'Noch nicht gespeichert';updateCounts(false)}
function updateCounts(markUnsaved=true){const clean=paragraph.value.trim();document.querySelector('#wordCount').textContent=clean?clean.split(/\s+/).length:0;document.querySelector('#charCount').textContent=paragraph.value.length;if(markUnsaved)status.textContent='Änderungen nicht gespeichert'}
paragraph.addEventListener('input',()=>updateCounts());
entryDate.addEventListener('change',loadEntry);
document.querySelector('#newPrompt').addEventListener('click',()=>{promptIndex=(promptIndex+1)%prompts.length;showPrompt()});
document.querySelector('#saveEntry').addEventListener('click',()=>{const review={};document.querySelectorAll('[data-review]').forEach(x=>review[x.dataset.review]=x.checked);writing[entryDate.value]={text:paragraph.value.trim(),review,savedAt:new Date().toISOString()};localStorage.setItem(WRITING_KEY,JSON.stringify(writing));status.textContent='Gespeichert ✓'});
document.querySelector('#copyForCorrection').addEventListener('click',async()=>{const text=paragraph.value.trim();const note=document.querySelector('#copyCorrectionStatus');if(!text){note.textContent='Schreibe zuerst einen Absatz.';return}const prompt='Bitte korrigiere meinen deutschen Text. Zeige mir: 1. eine korrigierte natürliche Version, 2. meine Fehler nach Kategorien (Rechtschreibung, Artikel/Endungen, Plural, Satzbau, Wortwahl), 3. drei kurze Übungen zu meinen häufigsten Fehlern. Text:\n\n'+text;await navigator.clipboard.writeText(prompt);note.textContent='Korrekturauftrag kopiert ✓'});
showPrompt();loadEntry();
const notes=JSON.parse(localStorage.getItem(NOTES_KEY)||'{}');
const notesDate=document.querySelector('#notesDate');const notesTitle=document.querySelector('#notesTitle');const dailyNotes=document.querySelector('#dailyNotes');const notesStatus=document.querySelector('#notesStatus');let notesTimer;
notesDate.value=day;
function formatNoteDate(date){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(date+'T12:00:00'))}
function renderNotesList(){const box=document.querySelector('#notesList');const dates=Object.keys(notes).filter(date=>notes[date]?.title||notes[date]?.text).sort().reverse();box.innerHTML=dates.length?dates.map(date=>`<button type="button" data-note-date="${date}" class="note-history-item${date===notesDate.value?' active':''}"><b>${esc(notes[date].title||'Notiz')}</b><span>${formatNoteDate(date)}</span></button>`).join(''):'<p class="notes-empty">Noch keine Notizen gespeichert.</p>';box.querySelectorAll('[data-note-date]').forEach(btn=>btn.addEventListener('click',()=>{notesDate.value=btn.dataset.noteDate;loadNote()}))}
function loadNote(){clearTimeout(notesTimer);const entry=notes[notesDate.value]||{};notesTitle.value=entry.title||'';dailyNotes.value=entry.text||'';notesStatus.textContent=entry.savedAt?'Gespeichert':'Noch nicht gespeichert';renderNotesList()}
function saveNote(auto=false){clearTimeout(notesTimer);const title=notesTitle.value.trim();const text=dailyNotes.value.trim();if(!title&&!text){notesStatus.textContent='Noch nichts zu speichern';return}notes[notesDate.value]={title,text,savedAt:new Date().toISOString()};localStorage.setItem(NOTES_KEY,JSON.stringify(notes));notesStatus.textContent=auto?'Automatisch gespeichert ✓':'Gespeichert ✓';renderNotesList()}
function queueNoteSave(){notesStatus.textContent='Wird gespeichert …';clearTimeout(notesTimer);notesTimer=setTimeout(()=>saveNote(true),700)}
notesTitle.addEventListener('input',queueNoteSave);dailyNotes.addEventListener('input',queueNoteSave);notesDate.addEventListener('change',loadNote);document.querySelector('#saveNote').addEventListener('click',()=>saveNote(false));document.querySelector('#deleteNote').addEventListener('click',()=>{if(!notes[notesDate.value])return;if(!window.confirm('Möchtest du diese Notiz wirklich löschen?'))return;delete notes[notesDate.value];localStorage.setItem(NOTES_KEY,JSON.stringify(notes));loadNote()});loadNote();
const verbs=window.GERMAN_VERBS;
let verbPerson=0;const verbDate=document.querySelector('#verbDate');const verbState=JSON.parse(localStorage.getItem(VERB_KEY)||'{}');verbDate.value=day;
const norm=s=>s.trim().toLocaleLowerCase('de-DE').replace(/\s+/g,' ');
function dailyVerbs(){const n=Math.floor(new Date(verbDate.value+'T12:00:00Z').getTime()/86400000);const start=(((n%verbs.length)+verbs.length)%verbs.length);return Array.from({length:5},(_,i)=>verbs[(start*5+i)%verbs.length])}
function verbAnswers(v){return[v.pr[verbPerson],v.pa[verbPerson],v.pe[verbPerson]]}
function renderVerbs(){const key=`${verbDate.value}-${verbPerson}`;const saved=verbState[key]||{};const box=document.querySelector('#verbCards');box.innerHTML='';dailyVerbs().forEach((v,i)=>{const values=saved[v.v]||['','',''];const card=document.createElement('article');card.className='verb-card';card.innerHTML=`<h3>${i+1}. ${v.v}</h3><span class="meaning">Alltagsverb</span>${['Präsens','Präteritum','Perfekt'].map((t,j)=>`<label class="verb-field"><span>${t}</span><input data-form="${j}" autocomplete="off" value="${values[j]||''}" placeholder="${j===2?'Hilfsverb + Partizip':'Verbform'}"><small class="verb-answer"></small></label>`).join('')}<button class="check-verb">Antwort prüfen</button>`;card.querySelectorAll('input').forEach((input,j)=>input.addEventListener('input',()=>{if(!verbState[key])verbState[key]={};verbState[key][v.v]=[...card.querySelectorAll('input')].map(x=>x.value);localStorage.setItem(VERB_KEY,JSON.stringify(verbState));input.classList.remove('correct','wrong');input.nextElementSibling.textContent=''}));card.querySelector('.check-verb').addEventListener('click',()=>checkVerb(card,v));box.append(card)});document.querySelector('#verbScore').textContent='0 von 15 Formen richtig'}
function checkVerb(card,v){const answers=verbAnswers(v);card.querySelectorAll('input').forEach((input,i)=>{const ok=norm(input.value)===norm(answers[i]);input.classList.toggle('correct',ok);input.classList.toggle('wrong',!ok);input.nextElementSibling.textContent=ok?'':`Richtig: ${answers[i]}`;if(!ok&&input.value.trim())logMistake('Verbform',input.value,answers[i])});const correct=document.querySelectorAll('.verb-card input.correct').length;document.querySelector('#verbScore').textContent=`${correct} von 15 Formen richtig`}
document.querySelectorAll('.person').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.person').forEach(x=>x.classList.remove('active'));btn.classList.add('active');verbPerson=+btn.dataset.person;renderVerbs()}));
verbDate.addEventListener('change',renderVerbs);document.querySelector('#clearVerbs').addEventListener('click',()=>{delete verbState[`${verbDate.value}-${verbPerson}`];localStorage.setItem(VERB_KEY,JSON.stringify(verbState));renderVerbs()});renderVerbs();
const nouns=window.GERMAN_NOUNS;
const articleDate=document.querySelector('#articleDate');const articleState=JSON.parse(localStorage.getItem(ARTICLE_KEY)||'{}');const articleMistakes=JSON.parse(localStorage.getItem(ARTICLE_MISTAKES_KEY)||'{}');articleDate.value=day;
function dailyNouns(){const n=Math.floor(new Date(articleDate.value+'T12:00:00Z').getTime()/86400000);const start=(((n%nouns.length)+nouns.length)%nouns.length);const base=Array.from({length:10},(_,i)=>nouns[(start*10+i)%nouns.length]);const due=Object.entries(articleMistakes).filter(([,v])=>v.count>0&&v.lastDate<articleDate.value).sort((a,b)=>b[1].count-a[1].count).slice(0,3).map(([name])=>nouns.find(x=>x[1]===name)).filter(Boolean);return[...due,...base.filter(x=>!due.some(d=>d[1]===x[1]))].slice(0,10)}
function renderArticles(){const saved=articleState[articleDate.value]||{};const box=document.querySelector('#articleCards');box.innerHTML='';dailyNouns().forEach(([answer,noun,plural],i)=>{const card=document.createElement('article');card.className='article-card';card.dataset.answer=answer;card.dataset.plural=plural||'';card.innerHTML=`<h3>${i+1}. ${noun}</h3><div class="article-choices">${['der','die','das'].map(a=>`<button class="article-choice${saved[noun]===a?' selected':''}" data-article="${a}">${a}</button>`).join('')}</div><small class="article-feedback"></small><small class="article-plural"></small>`;card.querySelectorAll('.article-choice').forEach(btn=>btn.addEventListener('click',()=>{card.querySelectorAll('.article-choice').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');if(!articleState[articleDate.value])articleState[articleDate.value]={};articleState[articleDate.value][noun]=btn.dataset.article;localStorage.setItem(ARTICLE_KEY,JSON.stringify(articleState));card.classList.remove('correct','wrong');card.querySelector('.article-feedback').textContent='';card.querySelector('.article-plural').textContent=''}));box.append(card)});document.querySelector('#articleScore').textContent='Noch nicht geprüft'}
function checkArticles(){let right=0;document.querySelectorAll('.article-card').forEach(card=>{const chosen=card.querySelector('.selected')?.dataset.article;const ok=chosen===card.dataset.answer;const noun=card.querySelector('h3').textContent.replace(/^\d+\.\s*/, '');card.classList.toggle('correct',ok);card.classList.toggle('wrong',!ok);if(ok){right++;if(articleMistakes[noun])articleMistakes[noun].count=Math.max(0,articleMistakes[noun].count-1)}else if(chosen){articleMistakes[noun]={count:(articleMistakes[noun]?.count||0)+1,lastDate:articleDate.value};logMistake('Artikel',chosen+' '+noun,card.dataset.answer+' '+noun)}card.querySelector('.article-feedback').textContent=ok?'Richtig ✓':`Richtig: ${card.dataset.answer}`;card.querySelector('.article-plural').textContent=card.dataset.plural?`Plural: die ${card.dataset.plural}`:''});localStorage.setItem(ARTICLE_MISTAKES_KEY,JSON.stringify(articleMistakes));document.querySelector('#articleScore').textContent=`${right} von 10 richtig`}
articleDate.addEventListener('change',renderArticles);document.querySelector('#checkArticles').addEventListener('click',checkArticles);document.querySelector('#clearArticles').addEventListener('click',()=>{delete articleState[articleDate.value];localStorage.setItem(ARTICLE_KEY,JSON.stringify(articleState));renderArticles()});renderArticles();
const corrections=window.GERMAN_CORRECTIONS;
const correctionDate=document.querySelector('#correctionDate');const correctionState=JSON.parse(localStorage.getItem(CORRECTION_KEY)||'{}');correctionDate.value=day;
function dailyCorrections(){const n=Math.floor(new Date(correctionDate.value+'T12:00:00Z').getTime()/86400000);const start=(((n%corrections.length)+corrections.length)%corrections.length);return Array.from({length:2},(_,i)=>corrections[(start*2+i)%corrections.length])}
function saveCorrections(){localStorage.setItem(CORRECTION_KEY,JSON.stringify(correctionState))}
function renderCorrections(){const saved=correctionState[correctionDate.value]||{};const box=document.querySelector('#correctionCards');box.innerHTML='';dailyCorrections().forEach((item,i)=>{const entry=saved[item.id]||{};const card=document.createElement('article');card.className='correction-card';card.innerHTML=`<span class="sentence-number">SATZ ${i+1}</span><blockquote>${item.wrong}</blockquote><label><span>Deine Korrektur</span><textarea lang="de" spellcheck="true" placeholder="Schreibe den vollständigen richtigen Satz …">${entry.text||''}</textarea></label><div class="correction-actions"><button class="reveal-answer">${entry.revealed?'Musterlösung ausblenden':'Musterlösung anzeigen'}</button></div><div class="model-answer${entry.revealed?' visible':''}"><span>MUSTERLÖSUNG</span><p>${item.correct}</p><small>${item.rule}</small><div><button data-rating="right" class="${entry.rating==='right'?'selected':''}">Das hatte ich richtig</button><button data-rating="practice" class="${entry.rating==='practice'?'selected':''}">Noch einmal üben</button></div></div>`;const textarea=card.querySelector('textarea');textarea.addEventListener('input',()=>{if(!correctionState[correctionDate.value])correctionState[correctionDate.value]={};correctionState[correctionDate.value][item.id]={...(correctionState[correctionDate.value][item.id]||{}),text:textarea.value};saveCorrections()});card.querySelector('.reveal-answer').addEventListener('click',e=>{if(!correctionState[correctionDate.value])correctionState[correctionDate.value]={};const current=correctionState[correctionDate.value][item.id]||{};current.revealed=!current.revealed;correctionState[correctionDate.value][item.id]=current;saveCorrections();renderCorrections()});card.querySelectorAll('[data-rating]').forEach(btn=>btn.addEventListener('click',()=>{if(!correctionState[correctionDate.value])correctionState[correctionDate.value]={};correctionState[correctionDate.value][item.id]={...(correctionState[correctionDate.value][item.id]||{}),rating:btn.dataset.rating,revealed:true};if(btn.dataset.rating==='practice')logMistake('Satzkorrektur',entry.text||item.wrong,item.correct);saveCorrections();renderCorrections()}));box.append(card)});const ratings=Object.values(saved).map(x=>x.rating).filter(Boolean);const right=ratings.filter(x=>x==='right').length;document.querySelector('#correctionScore').textContent=ratings.length?`${right} von 2 selbstständig korrigiert`:'Noch nicht bewertet'}
correctionDate.addEventListener('change',renderCorrections);document.querySelector('#clearCorrections').addEventListener('click',()=>{delete correctionState[correctionDate.value];saveCorrections();renderCorrections()});renderCorrections();
const errorLog=JSON.parse(localStorage.getItem(ERROR_LOG_KEY)||'{}');const labState=JSON.parse(localStorage.getItem(LAB_KEY)||'{}');const labDate=document.querySelector('#labDate');labDate.value=day;let activeLab='journal';
function logMistake(category,wrong,correct){const id=category+'|'+wrong+'|'+correct;const old=errorLog[id]||{category,wrong,correct,count:0};old.count++;old.lastDate=day;errorLog[id]=old;localStorage.setItem(ERROR_LOG_KEY,JSON.stringify(errorLog))}
function labItems(list,count){const n=Math.floor(new Date(labDate.value+'T12:00:00Z').getTime()/86400000);return Array.from({length:count},(_,i)=>list[((n*count+i)%list.length+list.length)%list.length])}
function renderJournal(){const rows=Object.entries(errorLog).sort((a,b)=>b[1].count-a[1].count);if(!rows.length)return '<div class="lab-empty"><b>Noch keine Fehler gespeichert</b><p>Fehler aus den Übungen erscheinen hier automatisch.</p></div>';return '<div class="journal-list">'+rows.slice(0,30).map(([id,x])=>`<article><span>${esc(x.category)}</span><div><s>${esc(x.wrong)}</s><b>${esc(x.correct)}</b></div><strong>${x.count}×</strong><button data-mastered="${encodeURIComponent(id)}">Gelernt</button></article>`).join('')+'</div>'}
function renderChoice(type,items){return '<div class="drill-grid">'+items.map((x,i)=>{const opts=type==='endings'?x[2].split('|'):[x[0],x[1]].sort(()=>i%2?1:-1);const prompt=type==='endings'?x[0]:'Welche Form ist richtig?';const answer=type==='endings'?x[1]:x[1];return `<article class="mini-drill" data-answer="${answer}" data-category="${type}"><span>AUFGABE ${i+1}</span><p>${prompt}</p><div>${opts.map(o=>`<button data-choice="${o}">${o}</button>`).join('')}</div><small></small></article>`}).join('')+'</div>'}
function renderConnectors(){return '<div class="drill-grid">'+labItems(ERROR_LAB.connectors,3).map((x,i)=>`<article class="mini-drill connector-drill"><span>SATZ ${i+1}</span><p>${x[0]}</p><textarea lang="de" spellcheck="true" placeholder="Schreibe den Satz richtig …"></textarea><button class="show-connector">Lösung zeigen</button><div class="connector-answer"><b>${x[1]}</b><small>${x[2]}</small></div></article>`).join('')+'</div>'}
function renderLab(){const box=document.querySelector('#labContent');if(activeLab==='journal')box.innerHTML=renderJournal();if(activeLab==='endings')box.innerHTML=renderChoice('endings',labItems(ERROR_LAB.endings,5));if(activeLab==='spelling')box.innerHTML=renderChoice('spelling',labItems(ERROR_LAB.spelling,5));if(activeLab==='natural')box.innerHTML=renderChoice('natural',labItems(ERROR_LAB.natural,3));if(activeLab==='connectors')box.innerHTML=renderConnectors();box.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.mini-drill');const ok=btn.dataset.choice===card.dataset.answer;card.querySelectorAll('[data-choice]').forEach(x=>x.classList.toggle('right',x.dataset.choice===card.dataset.answer));card.querySelector('small').textContent=ok?'Richtig ✓':'Merke dir die grün markierte Form.';if(!ok)logMistake(card.dataset.category==='endings'?'Endung':card.dataset.category==='spelling'?'Rechtschreibung':'Wortwahl',btn.dataset.choice,card.dataset.answer)}));box.querySelectorAll('.show-connector').forEach((btn,i)=>btn.addEventListener('click',()=>{btn.nextElementSibling.classList.toggle('visible');const item=labItems(ERROR_LAB.connectors,3)[i];if(btn.previousElementSibling.value.trim()&&norm(btn.previousElementSibling.value)!==norm(item[1]))logMistake('Satzbau',btn.previousElementSibling.value,item[1])}));box.querySelectorAll('[data-mastered]').forEach(btn=>btn.addEventListener('click',()=>{delete errorLog[decodeURIComponent(btn.dataset.mastered)];localStorage.setItem(ERROR_LOG_KEY,JSON.stringify(errorLog));renderLab()}))}
document.querySelectorAll('.lab-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.lab-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeLab=btn.dataset.lab;renderLab()}));labDate.addEventListener('change',renderLab);renderLab();
const VIEW_KEY='deutsch-c1-active-view-v1';
const viewMap={overview:['.intro','.site-summary','.grid','.roadmap'],writing:['.writing-studio'],verbs:['.verb-gym'],articles:['.article-gym'],correction:['.correction-gym'],notes:['.notes-studio'],lab:['.error-lab'],grammar:['.grammar-reference']};
const allViews=Object.values(viewMap).flatMap(selectors=>selectors.flatMap(s=>[...document.querySelectorAll(s)]));
function showView(name){if(!viewMap[name])name='overview';allViews.forEach(x=>x.hidden=true);viewMap[name].forEach(s=>document.querySelectorAll(s).forEach(x=>x.hidden=false));document.querySelectorAll('.main-tab').forEach(x=>{const on=x.dataset.view===name;x.classList.toggle('active',on);x.setAttribute('aria-selected',on)});localStorage.setItem(VIEW_KEY,name);window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go-view]').forEach(card=>card.addEventListener('click',()=>{const labTarget=card.dataset.goLab;if(labTarget){activeLab=labTarget;document.querySelectorAll('.lab-tab').forEach(x=>x.classList.toggle('active',x.dataset.lab===labTarget));renderLab()}showView(card.dataset.goView)}));
document.querySelectorAll('.main-tab').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));showView(localStorage.getItem(VIEW_KEY)||'overview');
render();save();
