const CORRECTION_PEOPLE=[
  {n:'Lukas',pro:'Er',pl:'er',pos:'sein',dat:'Ihm'},
  {n:'Mia',pro:'Sie',pl:'sie',pos:'ihr',dat:'Ihr'},
  {n:'Jonas',pro:'Er',pl:'er',pos:'sein',dat:'Ihm'},
  {n:'Lea',pro:'Sie',pl:'sie',pos:'ihr',dat:'Ihr'},
  {n:'David',pro:'Er',pl:'er',pos:'sein',dat:'Ihm'},
  {n:'Nora',pro:'Sie',pl:'sie',pos:'ihr',dat:'Ihr'},
  {n:'Tobias',pro:'Er',pl:'er',pos:'sein',dat:'Ihm'}
];
const CORRECTION_RULES=[
  {r:'Verb am Ende nach „weil“',w:p=>`${p.n} bleibt zu Hause, weil ${p.pl} ist müde.`,c:p=>`${p.n} bleibt zu Hause, weil ${p.pl} müde ist.`},
  {r:'Verb am Ende nach „dass“',w:p=>`${p.n} sagt, dass ${p.pl} kommt morgen später.`,c:p=>`${p.n} sagt, dass ${p.pl} morgen später kommt.`},
  {r:'Verb am Ende nach „obwohl“',w:p=>`${p.n} geht spazieren, obwohl es regnet stark.`,c:p=>`${p.n} geht spazieren, obwohl es stark regnet.`},
  {r:'Verb am Ende im wenn-Satz',w:p=>`${p.n} ruft mich an, wenn ${p.pl} hat Zeit.`,c:p=>`${p.n} ruft mich an, wenn ${p.pl} Zeit hat.`},
  {r:'Verb am Ende in der indirekten Frage',w:p=>`Ich weiß nicht, ob ${p.n} kann heute kommen.`,c:p=>`Ich weiß nicht, ob ${p.n} heute kommen kann.`},
  {r:'Nach einer Zeitangabe steht das Verb auf Position 2',w:p=>`Morgen ${p.n} arbeitet von zu Hause.`,c:p=>`Morgen arbeitet ${p.n} von zu Hause.`},
  {r:'Beim Modalverb steht der Infinitiv am Satzende',w:p=>`${p.n} muss heute früher nach Hause geht.`,c:p=>`${p.n} muss heute früher nach Hause gehen.`},
  {r:'Das Präfix steht im Hauptsatz am Ende',w:p=>`${p.n} anruft den Kunden am Nachmittag.`,c:p=>`${p.n} ruft den Kunden am Nachmittag an.`},
  {r:'Im Perfekt steht das Partizip am Satzende',w:p=>`${p.n} hat erledigt die Aufgabe schon.`,c:p=>`${p.n} hat die Aufgabe schon erledigt.`},
  {r:'„mit“ verlangt den Dativ',w:p=>`${p.n} fährt mit der Zug zur Arbeit.`,c:p=>`${p.n} fährt mit dem Zug zur Arbeit.`},
  {r:'„bei“ verlangt den Dativ',w:p=>`${p.n} arbeitet heute bei ein Kunde.`,c:p=>`${p.n} arbeitet heute bei einem Kunden.`},
  {r:'„für“ verlangt den Akkusativ',w:p=>`${p.n} fragt: „Ist das Geschenk für ${p.n === 'Mia' || p.n === 'Lea' || p.n === 'Nora' ? 'der neuen Kollegin' : 'der neue Kollege'}?“`,c:p=>`${p.n} fragt: „Ist das Geschenk für ${p.n === 'Mia' || p.n === 'Lea' || p.n === 'Nora' ? 'die neue Kollegin' : 'den neuen Kollegen'}?“`},
  {r:'„ohne“ verlangt den Akkusativ',w:p=>`${p.n} geht nie ohne ${p.pos} Regenschirm hinaus.`,c:p=>`${p.n} geht nie ohne ${p.pos}en Regenschirm hinaus.`},
  {r:'Ort: „in“ mit Dativ',w:p=>`${p.n} arbeitet gerade in das Büro.`,c:p=>`${p.n} arbeitet gerade in dem Büro.`},
  {r:'Bei „seit“ steht ein noch andauernder Zustand im Präsens',w:p=>`${p.n} hat seit drei Jahren in Berlin gewohnt.`,c:p=>`${p.n} wohnt seit drei Jahren in Berlin.`},
  {r:'Bewegungsverben bilden das Perfekt oft mit „sein“',w:p=>`${p.n} hat gestern früh nach Hause gegangen.`,c:p=>`${p.n} ist gestern früh nach Hause gegangen.`},
  {r:'„arbeiten“ bildet das Perfekt mit „haben“',w:p=>`${p.n} ist am Wochenende lange gearbeitet.`,c:p=>`${p.n} hat am Wochenende lange gearbeitet.`},
  {r:'„sich erinnern“ ist reflexiv',w:p=>`${p.n} erinnert an den Termin.`,c:p=>`${p.n} erinnert sich an den Termin.`},
  {r:'„warten“ steht mit „auf“ und Akkusativ',w:p=>`${p.n} wartet seit zehn Minuten für den Bus.`,c:p=>`${p.n} wartet seit zehn Minuten auf den Bus.`},
  {r:'Man spricht mit jemandem über etwas',w:p=>`${p.n} spricht den Chef über das Problem.`,c:p=>`${p.n} spricht mit dem Chef über das Problem.`},
  {r:'„helfen“ verlangt den Dativ',w:p=>`${p.n} hilft heute den neuen Kollegen.`,c:p=>`${p.n} hilft heute dem neuen Kollegen.`},
  {r:'„gefallen“ verlangt eine Person im Dativ',w:p=>`${p.n} sagt: „${p.pro} gefällt der neue Plan sehr.“`,c:p=>`${p.n} sagt: „${p.dat} gefällt der neue Plan sehr.“`},
  {r:'„zuhören“ verlangt den Dativ',w:p=>`${p.n} hört die Kollegin aufmerksam zu.`,c:p=>`${p.n} hört der Kollegin aufmerksam zu.`},
  {r:'„kein“ verneint ein Nomen ohne bestimmten Artikel',w:p=>`${p.n} hat nicht einen Führerschein.`,c:p=>`${p.n} hat keinen Führerschein.`},
  {r:'„nicht“ steht hier vor dem Adjektiv',w:p=>`${p.n} findet die Erklärung verständlich nicht.`,c:p=>`${p.n} findet die Erklärung nicht verständlich.`},
  {r:'Der Komparativ steht mit „als“',w:p=>`${p.n} ist heute entspannter wie gestern.`,c:p=>`${p.n} ist heute entspannter als gestern.`},
  {r:'Gleichheit wird mit „so … wie“ ausgedrückt',w:p=>`${p.n} arbeitet genauso sorgfältig als die Kollegin.`,c:p=>`${p.n} arbeitet genauso sorgfältig wie die Kollegin.`},
  {r:'Adjektivendung nach bestimmtem Artikel im Nominativ',w:p=>`${p.n} sagt, der neu Termin passt gut.`,c:p=>`${p.n} sagt, der neue Termin passt gut.`},
  {r:'Adjektivendung im Akkusativ',w:p=>`${p.n} braucht einen zuverlässig Computer.`,c:p=>`${p.n} braucht einen zuverlässigen Computer.`},
  {r:'Adjektivendung im Dativ',w:p=>`${p.n} spricht mit einem freundlich Mitarbeiter.`,c:p=>`${p.n} spricht mit einem freundlichen Mitarbeiter.`},
  {r:'Das Possessivpronomen richtet sich nach der Person',w:p=>`${p.n} hat ${p.pos === 'sein' ? 'ihre' : 'seine'} Schlüssel vergessen.`,c:p=>`${p.n} hat ${p.pos === 'sein' ? 'seine' : 'ihre'} Schlüssel vergessen.`},
  {r:'Nach „man“ steht das Verb in der 3. Person Singular',w:p=>`${p.n} meint, man müssen früher anfangen.`,c:p=>`${p.n} meint, man muss früher anfangen.`},
  {r:'Bei einem Plural-Subjekt steht das Verb im Plural',w:p=>`${p.n} sagt, die Kollegen kommt gleich.`,c:p=>`${p.n} sagt, die Kollegen kommen gleich.`},
  {r:'Dativ Plural: Das Nomen bekommt meist ein „-n“',w:p=>`${p.n} spricht mit den Kollege über den Plan.`,c:p=>`${p.n} spricht mit den Kollegen über den Plan.`},
  {r:'Im Relativsatz steht das Verb am Ende',w:p=>`${p.n} kennt die Frau, die arbeitet im Café.`,c:p=>`${p.n} kennt die Frau, die im Café arbeitet.`},
  {r:'In einer indirekten W-Frage steht das Verb am Ende',w:p=>`${p.n} fragt, wann beginnt die Besprechung.`,c:p=>`${p.n} fragt, wann die Besprechung beginnt.`},
  {r:'Bei gleichem Subjekt verwendet man „um … zu“',w:p=>`${p.n} lernt jeden Tag, damit besser Deutsch zu sprechen.`,c:p=>`${p.n} lernt jeden Tag, um besser Deutsch zu sprechen.`},
  {r:'„damit“ leitet einen Nebensatz mit eigenem Subjekt ein',w:p=>`${p.n} spricht langsam, um alle können alles verstehen.`,c:p=>`${p.n} spricht langsam, damit alle alles verstehen können.`},
  {r:'Höfliche Bitte mit Konjunktiv II',w:p=>`${p.n} sagt: „Können Sie mir bitte helfen würden?“`,c:p=>`${p.n} sagt: „Könnten Sie mir bitte helfen?“`},
  {r:'„gern“ steht normalerweise beim Verb',w:p=>`${p.n} mag Kaffee trinken gern.`,c:p=>`${p.n} trinkt gern Kaffee.`}
];
window.GERMAN_CORRECTIONS=CORRECTION_RULES.flatMap((rule,ruleIndex)=>CORRECTION_PEOPLE.map((person,personIndex)=>({id:`${ruleIndex}-${personIndex}`,wrong:rule.w(person),correct:rule.c(person),rule:rule.r})));
